# @format

name: Create Release
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  createPullRequest:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/create release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install
        run: yarn install
      - name: Git Identity
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      - name: Set Version Type
        id: type_check
        run: |
          if [${IS_PATCH}]; then
            echo "::set-output name=release_type::patch"
          elif [${IS_MINOR}]; then
            echo "::set-output name=release_type::minor"
          elif [${IS_MAJOR}]; then
            echo "::set-output name=release_type::major"
          else
            echo "::set-output name=release_type::patch"
          fi
        env:
          IS_PATCH: ${{startsWith(github.event.comment.body, '/create release patch')}}
          IS_MINOR: ${{startsWith(github.event.comment.body, '/create release minor')}}
          IS_MAJOR: ${{startsWith(github.event.comment.body, '/create release major')}}
      - name: Version Up
        run: yarn version --${{steps.type_check.release_type}}
      - name: Set current CHANGELOG to output
        id: changelog
        shell: bash -ex {0}
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update v${{ steps.changelog.outputs.version }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: "v${{ steps.changelog.outputs.version }}"
          body: |
            ## v${{ steps.changelog.outputs.version }}
            ### Breaking Changes
            - [ ] TODO
            ### Features
            - [ ] TODO
            ### Bug Fixes
            - [ ] TODO
          labels: "Type: Release"
          branch: "develop"
          base: "main"
          request-to-parent: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
