# @format

name: Create Release
on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  createPullRequest:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') &&
      startsWith(github.event.comment.body, '/create release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install
        run: yarn install
      - name: Git Identity
        run: |
          git config --global user.name '${GITHUB_ACTOR}'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
      # Define ${VERSION_TYPE}
      - name: Version Up
        run: echo "VERSION_TYPE=patch" >> $GITHUB_ENV
      - if: startsWith(github.event.comment.body, '/create release minor')
        run: echo "VERSION_TYPE=minor" >> $GITHUB_ENV
      - if: startsWith(github.event.comment.body, '/create release major')
        run: echo "VERSION_TYPE=major" >> $GITHUB_ENV
      - run: yarn version --${{env.VERSION_TYPE}} --no-git-tag-version
      - name: Set current CHANGELOG to output
        id: changelog
        shell: bash -ex {0}
        run: |
          version=$(node -p 'require("./package.json").version')
          echo "::set-output name=version::${version}"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update v${{ steps.changelog.outputs.version }}"
          committer: GitHub <noreply@github.com>
          author: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          title: "v${{ steps.changelog.outputs.version }}"
          body: |
            ## v${{ steps.changelog.outputs.version }}
            ### Breaking Changes
            - [ ] TODO
            ### Features
            - [ ] TODO
            ### Bug Fixes
            - [ ] TODO
          labels: "Type: Release"
          branch: "release/${{env.VERSION_TYPE}}"
          base: "main"
          delete-branch: true
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
